### ISSUE TITLE
Maybe use should instead of must on the topic of Restart=on-failure

### ISSUE THREAD

**Issue by CameronNemo** [ajtowns/debian-init-policy#7]
So you have this line:

```
Units MUST use Restart=on-failure or Restart=on-abnormal, as appropriate
```

there is a MUST clause, but it is immediately followed by a sort of cop out ("as appropiate").

Perhaps this would be better:

```
Units should use Restart=on-failure or Restart=on-abnormal when appropiate.
```

**Comment by ajtowns** [comment]
On 18 November 2014 17:34, Cameron Norman notifications@github.com wrote:

> So you have this line:
> 
> Units MUST use Restart=on-failure or Restart=on-abnormal, as appropriate
> 
> ​Where are you seeing that? The current version says:

   Units should use the <tt>Restart=</tt> directive to allow
   services to be automatically restarted if they crash. Using
   <tt>Restart=on-failure</tt> is the recommended way to do this,
   which will cause systemd to restart the service in the vast
   majority of error scenarios, but will not restart the service
   if it exits with an exit code of zero. Other options that may
   be worth considering are <tt>Restart=on-abnormal</tt> and
   <tt>Restart=always</tt>. Note that <tt>Restart=always</tt>
   will not allow socket-activated services to automatically
   stop when idle. (The way restarts are throttled can be
   configured configured by the <tt>StartLimitInterval</tt>
   and <tt>StartLimitBurst</tt> options)

​

https://github.com/ajtowns/debian-init-policy/blob/master/init-policy.sgml#L369-L380

​Cheers
​,
aj​

## 

Anthony Towns aj@erisian.com.au

**Comment by CameronNemo** [comment]
It was in the systemd-best-practices.pad. That must be out of date, sorry.
